PREFIX am: <http://www.imn.htwk-leipizg.de/~amatthes/semweb/schema#>

SELECT ?Region (SUM(?CrimeAmount) AS ?CrimeSum) (SUM(?PopAmount) AS ?UnempSum)
WHERE{
  ?crime am:hasCrimeDate ?Date .
  ?pop am:hasPopDate ?Date .
  
  ?crime am:hasCrimeCounty ?County .
  ?pop am:hasPopCounty ?County .
  ?County am:countyInRegion ?Region .
  
  ?crime am:hasCrimeAmount ?CrimeAmount .
  ?pop am:hasPopAmount ?PopAmount .
}
GROUP BY ?Region