PREFIX am: <http://www.imn.htwk-leipizg.de/~amatthes/semweb/schema#>

SELECT ?Date ?County (SUM(?CrimeAmount) AS ?CrimeSum)
WHERE{
  ?crime am:hasCrimeCounty ?County .
  ?crime am:hasCrimeAmount ?CrimeAmount .
  ?crime am:hasCrimeDate ?Date
}
GROUP BY ?Date ?County
ORDER BY DESC (?CrimeSum)